# Generated by Django 5.2.15 on 2026-07-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
